{
  config,
  lib,
  pkgs,
  ...
}: let
  privCfg = config.neet.security.privileges;
  cfg = config.neet.security.doas;
  isBackend = privCfg.backend == "doas";
in {
  options.neet.security.doas = {
    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.doas;
      description = "使用する doas パッケージ";
    };
  };

  config = lib.mkIf isBackend {
    neet.security.privileges.command = "/run/wrappers/bin/doas";

    environment.etc."doas.conf" = {
      mode = "0400";
      source = let
        rulesText =
          lib.concatMapStringsSep "\n" (
            rule: let
              asTarget =
                if rule.runAs == "ALL" || rule.runAs == "*"
                then ""
                else " as ${rule.runAs}";
              nopass = lib.optionalString (!rule.requirePassword) "nopass ";
              cmdStr =
                if rule.command == "ALL"
                then ""
                else " cmd ${rule.command}" + lib.optionalString (rule.args != "") " args ${rule.args}";
              ruleLine = id: "permit ${nopass}keepenv ${id}${asTarget}${cmdStr}";
            in ''
              ${lib.concatMapStringsSep "\n" (u: ruleLine (toString u)) rule.users}
              ${lib.concatMapStringsSep "\n" (g: ruleLine ":${toString g}") rule.groups}
            ''
          )
          privCfg.rules;

        rawContent = ''
          # Generated by NEET_OS (doas backend)
          permit ${lib.optionalString (!privCfg.wheelNeedsPassword) "nopass "}keepenv :wheel
          ${rulesText}
        '';
      in
        pkgs.runCommand "doas.conf-validated" {
          src = pkgs.writeText "doas.conf.in" rawContent;
        } ''
          ${pkgs.buildPackages.doas}/bin/doas -C $src && cp $src $out
        '';
    };

    neet.security.wrappers.doas = {
      source = "${cfg.package}/bin/doas";
      setuid = true;
      owner = "root";
      group = "root";
    };

    environment.systemPackages = [cfg.package];
  };
}
