{
  config,
  lib,
  pkgs,
  ...
}: let
  privCfg = config.neet.security.privileges;
  cfg = config.neet.security.sudo-rs;
  isBackend = privCfg.backend == "sudo-rs";
in {
  options.neet.security.sudo-rs = {
    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.sudo-rs;
      description = "使用する sudo-rs パッケージ";
    };
  };

  config = lib.mkIf isBackend {
    neet.security.privileges.command = "/run/wrappers/bin/sudo";

    environment.etc."sudoers" = {
      mode = "0440";
      source = let
        rulesText =
          lib.concatMapStringsSep "\n" (
            rule: let
              runAs =
                if rule.runAs == "*"
                then "ALL"
                else rule.runAs;
              opts = lib.optionalString (!rule.requirePassword) "NOPASSWD:";
              cmdStr = "${rule.command} ${rule.args}";
            in ''
              ${lib.concatMapStringsSep "\n" (u: "${u} ALL = (${runAs}) ${opts} ${cmdStr}") rule.users}
              ${lib.concatMapStringsSep "\n" (g: "%${g} ALL = (${runAs}) ${opts} ${cmdStr}") rule.groups}
            ''
          )
          privCfg.rules;

        rawContent = ''
          # Generated by NEET_OS (sudo-rs backend)
          Defaults env_keep += "HOME TERMINFO"

          root ALL=(ALL:ALL) ALL
          %wheel ALL=(ALL:ALL) ${
            if privCfg.wheelNeedsPassword
            then "ALL"
            else "NOPASSWD: ALL"
          }

          ${rulesText}
        '';
      in
        pkgs.runCommand "sudoers-validated" {
          src = pkgs.writeText "sudoers.in" rawContent;
        } "${pkgs.buildPackages.sudo-rs}/bin/visudo -f $src -c && cp $src $out";
    };

    neet.security.wrappers = {
      sudo = {
        source = "${cfg.package}/bin/sudo";
        setuid = true;
        owner = "root";
        group = "root";
      };
      sudoedit = {
        source = "${cfg.package}/bin/sudoedit";
        setuid = true;
        owner = "root";
        group = "root";
      };
    };

    environment.systemPackages = [cfg.package];
  };
}
