{
  config,
  lib,
  pkgs,
  ...
}: let
  # fstab エントリの文字列生成ヘルパー
  makeFstabEntries = fileSystems:
    lib.concatMapStringsSep "\n" (
      fs: "${fs.device} ${fs.mountPoint} ${fs.fsType} ${lib.concatStringsSep "," fs.options} ${toString fs.dump} ${toString fs.pass}"
    )
    fileSystems;

  # Stage 1 と Stage 2 の全マウントを統合（fstab 出力用）
  allFileSystems = lib.attrValues (
    config.boot.stage1.fileSystems // config.boot.stage2.fileSystems
  );
in {
  imports = [
    ./options.nix
    ./ext4.nix
    ./9p.nix
    ./special.nix
    ./tmpfs.nix
  ];

  config = {
    # Stage 2 向けのデフォルトマウント定義
    boot.stage2.fileSystems = {
      "/proc" = {
        device = "proc";
        fsType = "proc";
      };
      "/sys" = {
        device = "sysfs";
        fsType = "sysfs";
      };
      "/dev" = {
        device = "devtmpfs";
        fsType = "devtmpfs";
      };
      "/dev/pts" = {
        device = "devpts";
        fsType = "devpts";
        options = ["gid=5" "mode=620"];
      };
      "/dev/shm" = {
        device = "tmpfs";
        fsType = "tmpfs";
        options = ["mode=1777"];
      };
      "/run" = {
        device = "tmpfs";
        fsType = "tmpfs";
        options = ["mode=0755"];
      };
      "/tmp" = {
        device = "tmpfs";
        fsType = "tmpfs";
        options = ["mode=1777"];
      };

      # 原則2: ルート (/) は Stage 1 でマウント済みのため alreadyMounted = true を立てて宣言
      "/" = {
        device = "tmpfs";
        fsType = "tmpfs";
        alreadyMounted = true; # system-init はこれをパースしてスキップする
        pass = 1;
      };
    };

    # カーネルモジュールの自動判定
    boot.supportedFilesystems = let
      fsTypes = lib.unique (
        map (fs: fs.fsType) (lib.attrValues config.boot.stage2.fileSystems)
      );
      validFs =
        lib.filter (
          fs:
            fs
            != "auto"
            && fs != "proc"
            && fs != "sysfs"
            && fs != "devtmpfs"
            && fs != "tmpfs"
            && fs != "devpts"
        )
        fsTypes;
    in
      lib.genAttrs validFs (fs: {
        enable = true;
      });

    boot.initrd.supportedFilesystems = let
      fsTypes = lib.unique (
        map (fs: fs.fsType) (lib.attrValues config.boot.stage1.fileSystems)
      );
      validFs =
        lib.filter (
          fs:
            fs
            != "auto"
            && fs != "proc"
            && fs != "sysfs"
            && fs != "devtmpfs"
            && fs != "tmpfs"
        )
        fsTypes;
    in
      lib.genAttrs validFs (fs: {
        enable = true;
      });

    # 成果物の出力 (etc 経由)
    environment.etc = {
      # system-init (Rust) が読み込むマウント計画 (Stage 2 専用)
      "mount-plan.json".text = builtins.toJSON (
        lib.mapAttrs (name: fs: {
          inherit
            (fs)
            device
            mountPoint
            fsType
            options
            alreadyMounted
            dump
            pass
            ;
        })
        config.boot.stage2.fileSystems
      );

      # 全構造を可視化した fstab
      "fstab".text = ''
        # Generated by NEET-OS
        ${makeFstabEntries allFileSystems}
      '';
    };
  };
}
