{
  config,
  lib,
  pkgs,
  ...
}: let
  virtualFsTypes = ["auto" "proc" "sysfs" "devtmpfs" "tmpfs" "devpts"];
  computedStage1 = lib.filterAttrs (n: fs: fs.neededForBoot) config.boot.fileSystems;
  computedStage2 = lib.mapAttrs (n: fs: fs // {alreadyMounted = fs.neededForBoot or false;}) (
    config.boot.virtualFileSystems // config.boot.fileSystems
  );
  allFileSystems = lib.attrValues computedStage2;

  # Stage 1 用の mount-plan.json を生成する derivation
  stage1MountPlan = pkgs.writeText "stage1-mount-plan.json" (builtins.toJSON (
    lib.mapAttrs (name: fs: {
      inherit (fs) device mountPoint fsType options dump pass;
    })
    computedStage1
  ));
in {
  imports = [./options.nix ./btrfs.nix ./ext4.nix ./9p.nix ./special.nix ./tmpfs.nix];

  config = {
    # 成果物として system.build に持たせる
    system.build.stage1MountPlan = stage1MountPlan;

    boot.virtualFileSystems = {
      "/proc" = {
        device = "proc";
        fsType = "proc";
      };
      "/sys" = {
        device = "sysfs";
        fsType = "sysfs";
      };
      "/dev" = {
        device = "devtmpfs";
        fsType = "devtmpfs";
      };
      "/dev/pts" = {
        device = "devpts";
        fsType = "devpts";
        options = ["gid=5" "mode=620"];
      };
      "/dev/shm" = {
        device = "tmpfs";
        fsType = "tmpfs";
        options = ["mode=1777"];
      };
      "/run" = {
        device = "tmpfs";
        fsType = "tmpfs";
        options = ["mode=0755"];
      };
      "/tmp" = {
        device = "tmpfs";
        fsType = "tmpfs";
        options = ["mode=1777"];
      };
    };

    boot.supportedFilesystems = let
      fsTypes = lib.unique (map (fs: fs.fsType) (lib.attrValues config.boot.fileSystems));
      validFs = lib.filter (fs: !(builtins.elem fs virtualFsTypes)) fsTypes;
    in
      lib.mkDefault (lib.genAttrs validFs (fs: {enable = true;}));

    boot.initrd.supportedFilesystems = let
      fsTypes = lib.unique (map (fs: fs.fsType) (lib.attrValues computedStage1));
      validFs = lib.filter (fs: !(builtins.elem fs virtualFsTypes)) fsTypes;
    in
      lib.mkDefault (lib.genAttrs validFs (fs: {enable = true;}));

    environment.etc = {
      "mount-plan.json".text = builtins.toJSON (
        lib.mapAttrs (n: fs: {
          inherit (fs) device mountPoint fsType options alreadyMounted dump pass;
        })
        computedStage2
      );
      "fstab".text = ''
        # Generated by NEET-OS
        ${lib.concatMapStringsSep "\n"
          (fs: "${fs.device} ${fs.mountPoint} ${fs.fsType} ${lib.concatStringsSep "," fs.options} ${toString fs.dump} ${toString fs.pass}")
          allFileSystems}
      '';
    };
  };
}
