{
  config,
  lib,
  pkgs,
  ...
}: let
  makeFstabEntries = fileSystems:
    lib.concatMapStringsSep "\n" (
      fs: "${fs.device} ${fs.mountPoint} ${fs.fsType} ${lib.concatStringsSep "," fs.options} ${toString fs.dump} ${toString fs.pass}"
    )
    fileSystems;
in {
  imports = [./options.nix ./ext4.nix ./9p.nix ./special.nix ./tmpfs.nix];

  config = {
    fileSystems = {
      "/proc" = {fsType = "proc";};
      "/sys" = {fsType = "sysfs";};
      "/dev" = {fsType = "devtmpfs";};
      "/run" = {fsType = "tmpfs";};
      "/tmp" = {fsType = "tmpfs";};
    };

    # supportedFilesystems.<fs>.enable = true の形式に合わせる
    boot.supportedFilesystems = let
      fsTypes = lib.unique (lib.mapAttrsToList (n: v: v.fsType) config.fileSystems);
      validFs = lib.filter (fs: fs != "auto" && fs != "proc" && fs != "sysfs" && fs != "devtmpfs" && fs != "tmpfs") fsTypes;
    in
      lib.genAttrs validFs (fs: {enable = true;});

    # 2. Stage 1 (initrd) 側の全自動有効化
    # neededForBoot = true のファイルシステムから fsType を抽出し、initrd 側でも enable = true にする
    boot.initrd.supportedFilesystems = let
      neededFs = lib.filter (fs: fs.neededForBoot) (lib.attrValues config.fileSystems);
      fsTypes = lib.unique (map (fs: fs.fsType) neededFs);
      validFs = lib.filter (fs: fs != "auto" && fs != "proc" && fs != "sysfs" && fs != "devtmpfs" && fs != "tmpfs") fsTypes;
    in
      lib.genAttrs validFs (fs: {enable = true;});

    environment.etc."mount-plan.json".text = builtins.toJSON (
      lib.mapAttrs (name: fs: {
        inherit (fs) device mountPoint fsType options neededForBoot dump pass;
      })
      config.fileSystems
    );

    environment.etc."fstab".text = ''
      # Generated by NEET-OS
      ${makeFstabEntries (lib.attrValues config.fileSystems)}
    '';
  };
}
